const songs = [
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "Trap",
        "AudioFileId": "edr1u24i",
        "Title": "Rouge",
        "Description": "#Rouge #beats #producer #studio #flstudio #mpc #akai #numark #hiphop #rap #trap #swag #trill #production #soundcloud #abletonlive #remix #mix #artist #dj #djing #turntablism #download #musiclover #edm #rave #plur #fleek #psychomuzik #beatmaker #Trending #new",
        "Duration": 99.866,
        "Url": "https://clyp.it/edr1u24i",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/d92a6a97497a43e5b82286057db6a0b0.jpg",
        "Mp3Url": "http://a.clyp.it/edr1u24i.mp3",
        "SecureMp3Url": "https://a.clyp.it/edr1u24i.mp3",
        "OggUrl": "http://a.clyp.it/edr1u24i.ogg",
        "SecureOggUrl": "https://a.clyp.it/edr1u24i.ogg",
        "DateCreated": "2016-12-30T06:17:11.623"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "Trap",
        "AudioFileId": "cfisk45h",
        "Title": "southside type beat prod by Evol Beatz",
        "Description": "#fire #trap #hardaf",
        "Duration": 234.083,
        "Url": "https://clyp.it/cfisk45h",
        "Mp3Url": "http://a.clyp.it/cfisk45h.mp3",
        "SecureMp3Url": "https://a.clyp.it/cfisk45h.mp3",
        "OggUrl": "http://a.clyp.it/cfisk45h.ogg",
        "SecureOggUrl": "https://a.clyp.it/cfisk45h.ogg",
        "DateCreated": "2016-12-28T00:51:18.65"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "Trap",
        "AudioFileId": "4k2n4p15",
        "Title": "Metropolitain' (W.I.P) [ @rapidfiremuzik_official ]",
        "Description": "#producer #music #beats #hiphop #studio #edm #protools #rap #trap #soundcloud #studiolife #musicproducer #beatmaker #dj #ableton #instrumental #flgang #artist #beat #newmusic #rappers #mixtape #mixing #producerlife #producers #production #rnb #fruityloops #studioflow #housemusic #beatsforsale #instrumentals #house #maschine #rapper #logicpro #logic #bass #trapmusic #cubase #love #trapbeats #flstudio11 #instagood #rea",
        "Duration": 331.024,
        "Url": "https://clyp.it/4k2n4p15",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/82e8ac70f31947bdb53180187ed4c298.jpg",
        "Mp3Url": "http://a.clyp.it/4k2n4p15.mp3",
        "SecureMp3Url": "https://a.clyp.it/4k2n4p15.mp3",
        "OggUrl": "http://a.clyp.it/4k2n4p15.ogg",
        "SecureOggUrl": "https://a.clyp.it/4k2n4p15.ogg",
        "DateCreated": "2016-12-27T11:07:49.41"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "Trap",
        "AudioFileId": "iz2wy05c",
        "Title": "IT",
        "Description": "#rapmusic #hiphop #hiphophead #hiphopculture #hiphopbeat #hiphopjunkie #hiphoplife #bbn #idgt #artist #artists #artistic #lyric #lyrics #beat #flstudio #808mafia #piano #drums #bass #producer #producers #beatmaker #beatz #808 #trap #trapbeats #instrumentals #new #studioflow",
        "Duration": 113.058,
        "Url": "https://clyp.it/iz2wy05c",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/16ce2e23c63d40618a4291b9b89a4a35.jpg",
        "Mp3Url": "http://a.clyp.it/iz2wy05c.mp3",
        "SecureMp3Url": "https://a.clyp.it/iz2wy05c.mp3",
        "OggUrl": "http://a.clyp.it/iz2wy05c.ogg",
        "SecureOggUrl": "https://a.clyp.it/iz2wy05c.ogg",
        "DateCreated": "2016-12-27T05:45:27.003"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "Trap",
        "AudioFileId": "r0bf2kao",
        "Title": "escape",
        "Description": "#rapmusic #hiphop #hiphophead #hiphopculture #hiphopbeat #hiphopjunkie #hiphoplife #bbn #idgt #artist #artists #artistic #lyric #lyrics #beat #flstudio #808mafia #piano #drums #bass #producer #producers #beatmaker #beatz #808 #trap #trapbeats #instrumentals #new #studioflow",
        "Duration": 192,
        "Url": "https://clyp.it/r0bf2kao",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/a3b0cef2d3764f288683a342665d5496.jpg",
        "Mp3Url": "http://a.clyp.it/r0bf2kao.mp3",
        "SecureMp3Url": "https://a.clyp.it/r0bf2kao.mp3",
        "OggUrl": "http://a.clyp.it/r0bf2kao.ogg",
        "SecureOggUrl": "https://a.clyp.it/r0bf2kao.ogg",
        "DateCreated": "2016-12-27T05:36:38.747"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "Trap",
        "AudioFileId": "4e1xg0j3",
        "Title": "Oni$ / Yokai Split 4",
        "Description": "#trap #onis #yokai #sadboys",
        "Duration": 123.899,
        "Url": "https://clyp.it/4e1xg0j3",
        "Mp3Url": "http://a.clyp.it/4e1xg0j3.mp3",
        "SecureMp3Url": "https://a.clyp.it/4e1xg0j3.mp3",
        "OggUrl": "http://a.clyp.it/4e1xg0j3.ogg",
        "SecureOggUrl": "https://a.clyp.it/4e1xg0j3.ogg",
        "DateCreated": "2016-12-27T01:03:58.287"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "Trap",
        "AudioFileId": "f25i14og",
        "Title": "id 3 (w/ zyro)",
        "Description": "#trap #beat",
        "Duration": 50.573,
        "Url": "https://clyp.it/f25i14og",
        "Mp3Url": "http://a.clyp.it/f25i14og.mp3",
        "SecureMp3Url": "https://a.clyp.it/f25i14og.mp3",
        "OggUrl": "http://a.clyp.it/f25i14og.ogg",
        "SecureOggUrl": "https://a.clyp.it/f25i14og.ogg",
        "DateCreated": "2016-12-26T22:57:51.27"
    },
    {
        "Status": "Public",
        "CommentsEnabled": true,
        "Category": "Trap",
        "AudioFileId": "rbkadm5e",
        "Title": "Jusmo & Antokon - Devenir Maman",
        "Description": "#Sog #DevenirMaman #SonOfGodMusic #Trap",
        "Duration": 194.299,
        "Url": "https://clyp.it/rbkadm5e",
        "Mp3Url": "http://a.clyp.it/rbkadm5e.mp3",
        "SecureMp3Url": "https://a.clyp.it/rbkadm5e.mp3",
        "OggUrl": "http://a.clyp.it/rbkadm5e.ogg",
        "SecureOggUrl": "https://a.clyp.it/rbkadm5e.ogg",
        "DateCreated": "2016-12-26T04:08:48.693"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "Trap",
        "AudioFileId": "gbuerqln",
        "Title": "Notorious Christmas",
        "Description": "#Notorious #beats #producer #studio #flstudio #mpc #akai #numark #hiphop #rap #trap #swag #trill #production #soundcloud #abletonlive #remix #mix #artist #dj #djing #turntablism #download #musiclover #edm #rave #plur #fleek #psychomuzik #beatmaker #Trending #new",
        "Duration": 110.028,
        "Url": "https://clyp.it/gbuerqln",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/f5cfdfbaad3f49b5b659de23ea6553a5.jpg",
        "Mp3Url": "http://a.clyp.it/gbuerqln.mp3",
        "SecureMp3Url": "https://a.clyp.it/gbuerqln.mp3",
        "OggUrl": "http://a.clyp.it/gbuerqln.ogg",
        "SecureOggUrl": "https://a.clyp.it/gbuerqln.ogg",
        "DateCreated": "2016-12-25T21:58:05.797"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "Trap",
        "AudioFileId": "kjd3nbop",
        "Title": "PaniK",
        "Description": "#Trap #Beat #Instrumental #eNvision",
        "Duration": 107.912,
        "Url": "https://clyp.it/kjd3nbop",
        "Mp3Url": "http://a.clyp.it/kjd3nbop.mp3",
        "SecureMp3Url": "https://a.clyp.it/kjd3nbop.mp3",
        "OggUrl": "http://a.clyp.it/kjd3nbop.ogg",
        "SecureOggUrl": "https://a.clyp.it/kjd3nbop.ogg",
        "DateCreated": "2016-12-25T07:58:46.243"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "Trap",
        "AudioFileId": "lqu1n5mk",
        "Title": "Get Em",
        "Description": "#atliens #trap #808kick #bass #808sub",
        "Duration": 92.029,
        "Url": "https://clyp.it/lqu1n5mk",
        "Mp3Url": "http://a.clyp.it/lqu1n5mk.mp3",
        "SecureMp3Url": "https://a.clyp.it/lqu1n5mk.mp3",
        "OggUrl": "http://a.clyp.it/lqu1n5mk.ogg",
        "SecureOggUrl": "https://a.clyp.it/lqu1n5mk.ogg",
        "DateCreated": "2016-12-24T18:37:43.553"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "Trap",
        "AudioFileId": "t1o0yzvd",
        "Title": "We are number one (rip KM3 Remix)",
        "Description": "#trap",
        "Duration": 74.136,
        "Url": "https://clyp.it/t1o0yzvd",
        "Mp3Url": "http://a.clyp.it/t1o0yzvd.mp3",
        "SecureMp3Url": "https://a.clyp.it/t1o0yzvd.mp3",
        "OggUrl": "http://a.clyp.it/t1o0yzvd.ogg",
        "SecureOggUrl": "https://a.clyp.it/t1o0yzvd.ogg",
        "DateCreated": "2016-12-23T17:38:36.087"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "Trap",
        "AudioFileId": "njzbrmr3",
        "Title": "nekro",
        "Description": "#dark #trap #fml",
        "Duration": 51.749,
        "Url": "https://clyp.it/njzbrmr3",
        "Mp3Url": "http://a.clyp.it/njzbrmr3.mp3",
        "SecureMp3Url": "https://a.clyp.it/njzbrmr3.mp3",
        "OggUrl": "http://a.clyp.it/njzbrmr3.ogg",
        "SecureOggUrl": "https://a.clyp.it/njzbrmr3.ogg",
        "DateCreated": "2016-12-23T00:01:44.77"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "Trap",
        "AudioFileId": "zimsaave",
        "Title": "how to trap",
        "Description": "#trap #booty #twerk #twek",
        "Duration": 35.213,
        "Url": "https://clyp.it/zimsaave",
        "Mp3Url": "http://a.clyp.it/zimsaave.mp3",
        "SecureMp3Url": "https://a.clyp.it/zimsaave.mp3",
        "OggUrl": "http://a.clyp.it/zimsaave.ogg",
        "SecureOggUrl": "https://a.clyp.it/zimsaave.ogg",
        "DateCreated": "2016-12-22T21:57:36.937"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "Trap",
        "AudioFileId": "kn5dml42",
        "Title": "Gold Trap",
        "Description": "#Trap\nShoutout to waifubros and SAObros",
        "Duration": 134.975,
        "Url": "https://clyp.it/kn5dml42",
        "Mp3Url": "http://a.clyp.it/kn5dml42.mp3",
        "SecureMp3Url": "https://a.clyp.it/kn5dml42.mp3",
        "OggUrl": "http://a.clyp.it/kn5dml42.ogg",
        "SecureOggUrl": "https://a.clyp.it/kn5dml42.ogg",
        "DateCreated": "2016-12-22T19:15:25.36"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "Trap",
        "AudioFileId": "hn4v0o41",
        "Title": "pain",
        "Description": "#trap #nights #dreams #naruto #pain\nfollow me:\nhttps://twitter.com/skrrrrtnowitzki \nhttps://soundcloud.com/skrrrrtnowitzki\nhttps://instagram.com/skrrrrtnowitzki",
        "Duration": 169.848,
        "Url": "https://clyp.it/hn4v0o41",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/db9a46f48a5448e59360838263de2adc.jpg",
        "Mp3Url": "http://a.clyp.it/hn4v0o41.mp3",
        "SecureMp3Url": "https://a.clyp.it/hn4v0o41.mp3",
        "OggUrl": "http://a.clyp.it/hn4v0o41.ogg",
        "SecureOggUrl": "https://a.clyp.it/hn4v0o41.ogg",
        "DateCreated": "2016-12-22T07:42:41.29"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "Trap",
        "AudioFileId": "lmm4kgbj",
        "Title": "Yokai/Oni Split Tape - 01",
        "Description": "#yokai #onis #trap #sadboy2017",
        "Duration": 118.204,
        "Url": "https://clyp.it/lmm4kgbj",
        "Mp3Url": "http://a.clyp.it/lmm4kgbj.mp3",
        "SecureMp3Url": "https://a.clyp.it/lmm4kgbj.mp3",
        "OggUrl": "http://a.clyp.it/lmm4kgbj.ogg",
        "SecureOggUrl": "https://a.clyp.it/lmm4kgbj.ogg",
        "DateCreated": "2016-12-21T23:35:04.183"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "Trap",
        "AudioFileId": "p4ywscgj",
        "Title": "Yokai/Oni - Split - A",
        "Description": "#yokai #oni #trap #sadboys",
        "Duration": 246.047,
        "Url": "https://clyp.it/p4ywscgj",
        "Mp3Url": "http://a.clyp.it/p4ywscgj.mp3",
        "SecureMp3Url": "https://a.clyp.it/p4ywscgj.mp3",
        "OggUrl": "http://a.clyp.it/p4ywscgj.ogg",
        "SecureOggUrl": "https://a.clyp.it/p4ywscgj.ogg",
        "DateCreated": "2016-12-21T22:47:10.453"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "Trap",
        "AudioFileId": "ijhl5q5k",
        "Title": "BAD SLIME - BLUNTS (preview)",
        "Description": "#badslime #blunts #trap #weed #dubstep #rubixcubesolvingtypebeat #getthecopscalledonyoutypebeat",
        "Duration": 62.354,
        "Url": "https://clyp.it/ijhl5q5k",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/35381313418b40da9f703591450c9982.jpg",
        "Mp3Url": "http://a.clyp.it/ijhl5q5k.mp3",
        "SecureMp3Url": "https://a.clyp.it/ijhl5q5k.mp3",
        "OggUrl": "http://a.clyp.it/ijhl5q5k.ogg",
        "SecureOggUrl": "https://a.clyp.it/ijhl5q5k.ogg",
        "DateCreated": "2016-12-21T01:39:32.9"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "wip",
        "AudioFileId": "wrbs5ab2",
        "Title": "YESHAL",
        "Description": "#WIP",
        "Duration": 40.856,
        "Url": "https://clyp.it/wrbs5ab2",
        "Mp3Url": "http://a.clyp.it/wrbs5ab2.mp3",
        "SecureMp3Url": "https://a.clyp.it/wrbs5ab2.mp3",
        "OggUrl": "http://a.clyp.it/wrbs5ab2.ogg",
        "SecureOggUrl": "https://a.clyp.it/wrbs5ab2.ogg",
        "DateCreated": "2016-12-30T05:27:26.787"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "wip",
        "AudioFileId": "cgnxd2z1",
        "Title": "Trapstep #7",
        "Description": "#bluelama #trapstep #wip",
        "Duration": 103.915,
        "Url": "https://clyp.it/cgnxd2z1",
        "Mp3Url": "http://a.clyp.it/cgnxd2z1.mp3",
        "SecureMp3Url": "https://a.clyp.it/cgnxd2z1.mp3",
        "OggUrl": "http://a.clyp.it/cgnxd2z1.ogg",
        "SecureOggUrl": "https://a.clyp.it/cgnxd2z1.ogg",
        "DateCreated": "2016-12-30T00:19:18.76"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "wip",
        "AudioFileId": "hmw1v0cc",
        "Title": "hell V1",
        "Description": "#WIP",
        "Duration": 233.195,
        "Url": "https://clyp.it/hmw1v0cc",
        "Mp3Url": "http://a.clyp.it/hmw1v0cc.mp3",
        "SecureMp3Url": "https://a.clyp.it/hmw1v0cc.mp3",
        "OggUrl": "http://a.clyp.it/hmw1v0cc.ogg",
        "SecureOggUrl": "https://a.clyp.it/hmw1v0cc.ogg",
        "DateCreated": "2016-12-29T23:39:34.963"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": false,
        "Category": "wip",
        "AudioFileId": "gbffewbk",
        "Title": "What are you doing new year's eve - ukulele project",
        "Description": "#bagongtaon #WIP #givemeachance #zooeydeschanel #josephgordonlevitt #ukulele #practice #holidayjam #projecthappiness #2016goals",
        "Duration": 101.564,
        "Url": "https://clyp.it/gbffewbk",
        "Mp3Url": "http://a.clyp.it/gbffewbk.mp3",
        "SecureMp3Url": "https://a.clyp.it/gbffewbk.mp3",
        "OggUrl": "http://a.clyp.it/gbffewbk.ogg",
        "SecureOggUrl": "https://a.clyp.it/gbffewbk.ogg",
        "DateCreated": "2016-12-29T17:43:20.507"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": false,
        "Category": "wip",
        "AudioFileId": "pozz2mx2",
        "Title": "Bawat eskinita - ukulele project",
        "Description": "#bawatdaan #WIP #ebedancel #ukulele #practice #holidayjam #projecthappiness #2016goals",
        "Duration": 107.285,
        "Url": "https://clyp.it/pozz2mx2",
        "Mp3Url": "http://a.clyp.it/pozz2mx2.mp3",
        "SecureMp3Url": "https://a.clyp.it/pozz2mx2.mp3",
        "OggUrl": "http://a.clyp.it/pozz2mx2.ogg",
        "SecureOggUrl": "https://a.clyp.it/pozz2mx2.ogg",
        "DateCreated": "2016-12-29T17:35:22.303"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "wip",
        "AudioFileId": "vlhukzqh",
        "Title": "Outisde Beta",
        "Description": "#wip",
        "Duration": 323.997,
        "Url": "https://clyp.it/vlhukzqh",
        "Mp3Url": "http://a.clyp.it/vlhukzqh.mp3",
        "SecureMp3Url": "https://a.clyp.it/vlhukzqh.mp3",
        "OggUrl": "http://a.clyp.it/vlhukzqh.ogg",
        "SecureOggUrl": "https://a.clyp.it/vlhukzqh.ogg",
        "DateCreated": "2016-12-29T15:28:25.74"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "wip",
        "AudioFileId": "kw2iekzd",
        "Title": "09 wip",
        "Description": "#Wip",
        "Duration": 166.113,
        "Url": "https://clyp.it/kw2iekzd",
        "Mp3Url": "http://a.clyp.it/kw2iekzd.mp3",
        "SecureMp3Url": "https://a.clyp.it/kw2iekzd.mp3",
        "OggUrl": "http://a.clyp.it/kw2iekzd.ogg",
        "SecureOggUrl": "https://a.clyp.it/kw2iekzd.ogg",
        "DateCreated": "2016-12-28T03:01:50.017"
    },
    {
        "Status": "Public",
        "CommentsEnabled": true,
        "Category": "wip",
        "AudioFileId": "vsyijcuv",
        "Title": "Stuff 310",
        "Description": "#ThePal #wip #flstudio",
        "Duration": 59.141,
        "Url": "https://clyp.it/vsyijcuv",
        "Mp3Url": "http://a.clyp.it/vsyijcuv.mp3",
        "SecureMp3Url": "https://a.clyp.it/vsyijcuv.mp3",
        "OggUrl": "http://a.clyp.it/vsyijcuv.ogg",
        "SecureOggUrl": "https://a.clyp.it/vsyijcuv.ogg",
        "DateCreated": "2016-12-28T02:59:34.837"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "wip",
        "AudioFileId": "xw5nuwqq",
        "Title": "Remeniscence (Simplified)",
        "Description": "#Piano #WIP",
        "Duration": 244.036,
        "Url": "https://clyp.it/xw5nuwqq",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/81d92f75dd1e46aeae0046e0e789b48b.jpg",
        "Mp3Url": "http://a.clyp.it/xw5nuwqq.mp3",
        "SecureMp3Url": "https://a.clyp.it/xw5nuwqq.mp3",
        "OggUrl": "http://a.clyp.it/xw5nuwqq.ogg",
        "SecureOggUrl": "https://a.clyp.it/xw5nuwqq.ogg",
        "DateCreated": "2016-12-27T15:08:07.507"
    },
    {
        "Status": "Public",
        "CommentsEnabled": true,
        "Category": "wip",
        "AudioFileId": "ajemunkx",
        "Title": "Stuff 309",
        "Description": "#ThePal #wip #flstudio",
        "Duration": 98.011,
        "Url": "https://clyp.it/ajemunkx",
        "Mp3Url": "http://a.clyp.it/ajemunkx.mp3",
        "SecureMp3Url": "https://a.clyp.it/ajemunkx.mp3",
        "OggUrl": "http://a.clyp.it/ajemunkx.ogg",
        "SecureOggUrl": "https://a.clyp.it/ajemunkx.ogg",
        "DateCreated": "2016-12-26T22:58:01.437"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "wip",
        "AudioFileId": "tir200en",
        "Title": "wierd synth V1",
        "Description": "#WIP",
        "Duration": 207.334,
        "Url": "https://clyp.it/tir200en",
        "Mp3Url": "http://a.clyp.it/tir200en.mp3",
        "SecureMp3Url": "https://a.clyp.it/tir200en.mp3",
        "OggUrl": "http://a.clyp.it/tir200en.ogg",
        "SecureOggUrl": "https://a.clyp.it/tir200en.ogg",
        "DateCreated": "2016-12-25T21:57:26.583"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "wip",
        "AudioFileId": "pnnx1sbu",
        "Title": "Kill Yourself wip",
        "Description": "#wip\n#edgy\n#whatgenreisthis",
        "Duration": 36.206,
        "Url": "https://clyp.it/pnnx1sbu",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/61d9e66266d14619a09900a3adaae750.jpg",
        "Mp3Url": "http://a.clyp.it/pnnx1sbu.mp3",
        "SecureMp3Url": "https://a.clyp.it/pnnx1sbu.mp3",
        "OggUrl": "http://a.clyp.it/pnnx1sbu.ogg",
        "SecureOggUrl": "https://a.clyp.it/pnnx1sbu.ogg",
        "DateCreated": "2016-12-25T21:33:50.197"
    },
    {
        "Status": "Public",
        "CommentsEnabled": true,
        "Category": "wip",
        "AudioFileId": "iqmdcbut",
        "Title": "Stuff 307",
        "Description": "#ThePal #wip #flstudio",
        "Duration": 44.356,
        "Url": "https://clyp.it/iqmdcbut",
        "Mp3Url": "http://a.clyp.it/iqmdcbut.mp3",
        "SecureMp3Url": "https://a.clyp.it/iqmdcbut.mp3",
        "OggUrl": "http://a.clyp.it/iqmdcbut.ogg",
        "SecureOggUrl": "https://a.clyp.it/iqmdcbut.ogg",
        "DateCreated": "2016-12-24T22:35:43.86"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "wip",
        "AudioFileId": "5vvdcxgs",
        "Title": "One Day V3",
        "Description": "#WIP",
        "Duration": 158.198,
        "Url": "https://clyp.it/5vvdcxgs",
        "Mp3Url": "http://a.clyp.it/5vvdcxgs.mp3",
        "SecureMp3Url": "https://a.clyp.it/5vvdcxgs.mp3",
        "OggUrl": "http://a.clyp.it/5vvdcxgs.ogg",
        "SecureOggUrl": "https://a.clyp.it/5vvdcxgs.ogg",
        "DateCreated": "2016-12-24T17:51:38.227"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "wip",
        "AudioFileId": "55ur3pkn",
        "Title": "One Day V2",
        "Description": "#WIP",
        "Duration": 158.198,
        "Url": "https://clyp.it/55ur3pkn",
        "Mp3Url": "http://a.clyp.it/55ur3pkn.mp3",
        "SecureMp3Url": "https://a.clyp.it/55ur3pkn.mp3",
        "OggUrl": "http://a.clyp.it/55ur3pkn.ogg",
        "SecureOggUrl": "https://a.clyp.it/55ur3pkn.ogg",
        "DateCreated": "2016-12-24T17:45:54.92"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "wip",
        "AudioFileId": "02ct4lhj",
        "Title": "gratzjxkvapsd",
        "Description": "you made it lel #oldpiece #wip",
        "Duration": 148.193,
        "Url": "https://clyp.it/02ct4lhj",
        "Mp3Url": "http://a.clyp.it/02ct4lhj.mp3",
        "SecureMp3Url": "https://a.clyp.it/02ct4lhj.mp3",
        "OggUrl": "http://a.clyp.it/02ct4lhj.ogg",
        "SecureOggUrl": "https://a.clyp.it/02ct4lhj.ogg",
        "DateCreated": "2016-12-22T15:14:53.447"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "wip",
        "AudioFileId": "cte3gcnm",
        "Title": "Melodic Dubstep Idea",
        "Description": "No where near done, just an idea.\nhttps://soundcloud.com/riptydez\n\n#Dubstep #Melodic #Bass #Wip #Draft #Idea #WorldsShittiestMix",
        "Duration": 101.198,
        "Url": "https://clyp.it/cte3gcnm",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/225d9e78243749b1be0c11a2e3f35792.jpg",
        "Mp3Url": "http://a.clyp.it/cte3gcnm.mp3",
        "SecureMp3Url": "https://a.clyp.it/cte3gcnm.mp3",
        "OggUrl": "http://a.clyp.it/cte3gcnm.ogg",
        "SecureOggUrl": "https://a.clyp.it/cte3gcnm.ogg",
        "DateCreated": "2016-12-21T10:33:25.32"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "wip",
        "AudioFileId": "q3thdlam",
        "Title": "Delivery.",
        "Description": "#wip Congratulations. This is your fault, you fickle vigilantes.",
        "Duration": 179.278,
        "Url": "https://clyp.it/q3thdlam",
        "Mp3Url": "http://a.clyp.it/q3thdlam.mp3",
        "SecureMp3Url": "https://a.clyp.it/q3thdlam.mp3",
        "OggUrl": "http://a.clyp.it/q3thdlam.ogg",
        "SecureOggUrl": "https://a.clyp.it/q3thdlam.ogg",
        "DateCreated": "2016-12-20T05:08:08.48"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "wip",
        "AudioFileId": "k5gnxtyl",
        "Title": "Antlers-esque",
        "Description": "#wip",
        "Duration": 160.052,
        "Url": "https://clyp.it/k5gnxtyl",
        "Mp3Url": "http://a.clyp.it/k5gnxtyl.mp3",
        "SecureMp3Url": "https://a.clyp.it/k5gnxtyl.mp3",
        "OggUrl": "http://a.clyp.it/k5gnxtyl.ogg",
        "SecureOggUrl": "https://a.clyp.it/k5gnxtyl.ogg",
        "DateCreated": "2016-12-18T20:59:55.787"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "chicago",
        "AudioFileId": "b1s0gtox",
        "Title": "SHOTS FIRED AT THE POLICE  10-1",
        "Description": "#SpotNewsOnIG #chicago #ShotsFiredAtThePolice #Chicago #Techicago #PoliceEmergency #ShotsFired",
        "Duration": 543.739,
        "Url": "https://clyp.it/b1s0gtox",
        "Mp3Url": "http://a.clyp.it/b1s0gtox.mp3",
        "SecureMp3Url": "https://a.clyp.it/b1s0gtox.mp3",
        "OggUrl": "http://a.clyp.it/b1s0gtox.ogg",
        "SecureOggUrl": "https://a.clyp.it/b1s0gtox.ogg",
        "DateCreated": "2016-12-07T02:11:34.58"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "chicago",
        "AudioFileId": "hbdzjn0s",
        "Title": "Zone 8: 10-1, shots fired at the police 86th/May",
        "Description": "Audio from Zone 8 via CrimeIsDown.com. Starts at 7:32pm.\n\n#chicago #CrimeIsDown",
        "Duration": 674.664,
        "Url": "https://clyp.it/hbdzjn0s",
        "Mp3Url": "http://a.clyp.it/hbdzjn0s.mp3",
        "SecureMp3Url": "https://a.clyp.it/hbdzjn0s.mp3",
        "OggUrl": "http://a.clyp.it/hbdzjn0s.ogg",
        "SecureOggUrl": "https://a.clyp.it/hbdzjn0s.ogg",
        "DateCreated": "2016-12-07T01:57:35.167"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "chicago",
        "AudioFileId": "3v1qeo0s",
        "Title": "Zone 8: 10-1, shots fired at the police, HBT",
        "Description": "Audio starts at 10:18pm on 12/1/2016, from Zone 8 via Broadcastify.com\n\nStory: http://www.chicagotribune.com/news/local/breaking/ct-swat-on-scene-of-standoff-in-south-chicago-20161201-story.html\n\n#chicago #CrimeIsDown",
        "Duration": 1271.458,
        "Url": "https://clyp.it/3v1qeo0s",
        "Mp3Url": "http://a.clyp.it/3v1qeo0s.mp3",
        "SecureMp3Url": "https://a.clyp.it/3v1qeo0s.mp3",
        "OggUrl": "http://a.clyp.it/3v1qeo0s.ogg",
        "SecureOggUrl": "https://a.clyp.it/3v1qeo0s.ogg",
        "DateCreated": "2016-12-02T17:20:00.637"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "chicago",
        "AudioFileId": "zok1r3mn",
        "Title": "Zone 6: 10-1, shots fired at CPD and FBI",
        "Description": "Audio starts at 9:24am, from Zone 6 via Broadcastify.com\n\n4 offenders in custody after firing shots at law enforcement.\n\nSTORY: http://www.chicagotribune.com/news/local/breaking/ct-police-search-neighborhood-near-midway-airport-after-shots-fired-at-officers-20161128-story.html\n\n#chicago #CrimeIsDown",
        "Duration": 4849.607,
        "Url": "https://clyp.it/zok1r3mn",
        "Mp3Url": "http://a.clyp.it/zok1r3mn.mp3",
        "SecureMp3Url": "https://a.clyp.it/zok1r3mn.mp3",
        "OggUrl": "http://a.clyp.it/zok1r3mn.ogg",
        "SecureOggUrl": "https://a.clyp.it/zok1r3mn.ogg",
        "DateCreated": "2016-11-29T03:05:37.027"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "chicago",
        "AudioFileId": "ulqwykqy",
        "Title": "Zone 10: 10-1, shots fired at and by the police",
        "Description": "Audio starts at 11:18pm 11/27/2016, recording via CrimeIsDown.com\n**Jump to 10:00 in the recording for the 10-1**\n\nStarts out as a person shot near 4700 W Adams, but 10 minutes later shots are fired at CPD near Madison/Kenton and a 10-1 is called.\n\nFrom the 10-1, one offender shot by CPD and two CPD officers injured.\n\n#chicago #CrimeIsDown",
        "Duration": 2479.961,
        "Url": "https://clyp.it/ulqwykqy",
        "Mp3Url": "http://a.clyp.it/ulqwykqy.mp3",
        "SecureMp3Url": "https://a.clyp.it/ulqwykqy.mp3",
        "OggUrl": "http://a.clyp.it/ulqwykqy.ogg",
        "SecureOggUrl": "https://a.clyp.it/ulqwykqy.ogg",
        "DateCreated": "2016-11-28T06:08:57.037"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "chicago",
        "AudioFileId": "xr0cyayp",
        "Title": "5 shot at a party, 88th/Exchange",
        "Description": "Starts at 2:13am on Zone 8, audio via Broadcastify.\n\n#chicago #CrimeIsDown",
        "Duration": 1898.553,
        "Url": "https://clyp.it/xr0cyayp",
        "Mp3Url": "http://a.clyp.it/xr0cyayp.mp3",
        "SecureMp3Url": "https://a.clyp.it/xr0cyayp.mp3",
        "OggUrl": "http://a.clyp.it/xr0cyayp.ogg",
        "SecureOggUrl": "https://a.clyp.it/xr0cyayp.ogg",
        "DateCreated": "2016-11-26T09:05:01.513"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "chicago",
        "AudioFileId": "n5xqmawg",
        "Title": "10-1, shots fired by the police at 65th and Marshfield",
        "Description": "Starts at 11:06pm on 11/23/2016, audio from Zone 6 via CrimeIsDown.com.\n\nStory: http://chicago.suntimes.com/news/person-shot-by-chicago-police-in-west-englewood/\n\n#chicago #CrimeIsDown",
        "Duration": 477.456,
        "Url": "https://clyp.it/n5xqmawg",
        "Mp3Url": "http://a.clyp.it/n5xqmawg.mp3",
        "SecureMp3Url": "https://a.clyp.it/n5xqmawg.mp3",
        "OggUrl": "http://a.clyp.it/n5xqmawg.ogg",
        "SecureOggUrl": "https://a.clyp.it/n5xqmawg.ogg",
        "DateCreated": "2016-11-24T06:51:02.433"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "chicago",
        "AudioFileId": "b5pizryc",
        "Title": "Happy Thanksgiving from Supt. Johnson, Car 3",
        "Description": "Starts at 3:26pm on Zone 4. Audio via CrimeIsDown.com.\n\n#chicago",
        "Duration": 60.6,
        "Url": "https://clyp.it/b5pizryc",
        "Mp3Url": "http://a.clyp.it/b5pizryc.mp3",
        "SecureMp3Url": "https://a.clyp.it/b5pizryc.mp3",
        "OggUrl": "http://a.clyp.it/b5pizryc.ogg",
        "SecureOggUrl": "https://a.clyp.it/b5pizryc.ogg",
        "DateCreated": "2016-11-22T21:55:23.66"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "chicago",
        "AudioFileId": "2euvdtkx",
        "Title": "YOUNG AFFISHAL SHOT AND KILLED",
        "Description": "#SpotNewsOnIG #MatthewRodgers #Y13137 #YoungAffishal #chicago #Homicide #Shooting #Chicago",
        "Duration": 501.812,
        "Url": "https://clyp.it/2euvdtkx",
        "Mp3Url": "http://a.clyp.it/2euvdtkx.mp3",
        "SecureMp3Url": "https://a.clyp.it/2euvdtkx.mp3",
        "OggUrl": "http://a.clyp.it/2euvdtkx.ogg",
        "SecureOggUrl": "https://a.clyp.it/2euvdtkx.ogg",
        "DateCreated": "2016-11-20T19:05:09.977"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "chicago",
        "AudioFileId": "vs4xzorv",
        "Title": "69th/Damen: 10-1, Shots Fired By The Police",
        "Description": "Starts at 11:38pm on 11/19/2016. Audio from Zone 6 via Broadcastify.\n\nDetails pending. CPD PIO tweet: https://twitter.com/AJGuglielmi/status/799861489653968896\n\n#chicago #CrimeIsDown",
        "Duration": 674.247,
        "Url": "https://clyp.it/vs4xzorv",
        "Mp3Url": "http://a.clyp.it/vs4xzorv.mp3",
        "SecureMp3Url": "https://a.clyp.it/vs4xzorv.mp3",
        "OggUrl": "http://a.clyp.it/vs4xzorv.ogg",
        "SecureOggUrl": "https://a.clyp.it/vs4xzorv.ogg",
        "DateCreated": "2016-11-19T06:46:15.147"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "chicago",
        "AudioFileId": "2r5eykav",
        "Title": "Zone 6 pursuit of homicide suspect, crash",
        "Description": "Starts at 11:38am, audio from Zone 6 via CrimeIsDown.com\n#chicago #CrimeIsDown",
        "Duration": 753.216,
        "Url": "https://clyp.it/2r5eykav",
        "Mp3Url": "http://a.clyp.it/2r5eykav.mp3",
        "SecureMp3Url": "https://a.clyp.it/2r5eykav.mp3",
        "OggUrl": "http://a.clyp.it/2r5eykav.ogg",
        "SecureOggUrl": "https://a.clyp.it/2r5eykav.ogg",
        "DateCreated": "2016-11-15T17:49:10.92"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "chicago",
        "AudioFileId": "4fpn2rpd",
        "Title": "I thought we could pursue for a Agg-UUW?",
        "Description": "#SpotNewsOnIG #Chicago #chicago #ShitCPDSays  #PursuitPolicy #CPD",
        "Duration": 52.088,
        "Url": "https://clyp.it/4fpn2rpd",
        "Mp3Url": "http://a.clyp.it/4fpn2rpd.mp3",
        "SecureMp3Url": "https://a.clyp.it/4fpn2rpd.mp3",
        "OggUrl": "http://a.clyp.it/4fpn2rpd.ogg",
        "SecureOggUrl": "https://a.clyp.it/4fpn2rpd.ogg",
        "DateCreated": "2016-11-08T05:29:37.64"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "chicago",
        "AudioFileId": "3a0zder3",
        "Title": "Scanner Audio: Shots fired at CPD, pursuit",
        "Description": "Zone 10 audio via Broadcastify. Starts at 12:49pm.\n\nTwitter thread: https://twitter.com/EricTendian/status/795700826555772929\n\n#chicago #CrimeIsDown",
        "Duration": 1417.535,
        "Url": "https://clyp.it/3a0zder3",
        "Mp3Url": "http://a.clyp.it/3a0zder3.mp3",
        "SecureMp3Url": "https://a.clyp.it/3a0zder3.mp3",
        "OggUrl": "http://a.clyp.it/3a0zder3.ogg",
        "SecureOggUrl": "https://a.clyp.it/3a0zder3.ogg",
        "DateCreated": "2016-11-07T19:35:09.693"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "chicago",
        "AudioFileId": "c35kg5id",
        "Title": "Zone 9: Shots fired at and by the police, 111th and Troy",
        "Description": "Starts at 3:04pm. Recording via Broadcastify.\n#chicago #CrimeIsDown",
        "Duration": 1215.06,
        "Url": "https://clyp.it/c35kg5id",
        "Mp3Url": "http://a.clyp.it/c35kg5id.mp3",
        "SecureMp3Url": "https://a.clyp.it/c35kg5id.mp3",
        "OggUrl": "http://a.clyp.it/c35kg5id.ogg",
        "SecureOggUrl": "https://a.clyp.it/c35kg5id.ogg",
        "DateCreated": "2016-11-05T20:39:06.963"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "chicago",
        "AudioFileId": "iklqpshb",
        "Title": "WANTED FOR MURDER",
        "Description": "#SpotNewsOnIG #chicago #Wanted #Chicago #Murder #AllCall #WantedForMurder #ShitOEMCSays #CPD #BOLO",
        "Duration": 76.722,
        "Url": "https://clyp.it/iklqpshb",
        "Mp3Url": "http://a.clyp.it/iklqpshb.mp3",
        "SecureMp3Url": "https://a.clyp.it/iklqpshb.mp3",
        "OggUrl": "http://a.clyp.it/iklqpshb.ogg",
        "SecureOggUrl": "https://a.clyp.it/iklqpshb.ogg",
        "DateCreated": "2016-11-04T14:11:28.163"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "chicago",
        "AudioFileId": "j2rfy52z",
        "Title": "AIN'T NO DIFFERENT THAN THE SOUTH SIDE",
        "Description": "#SpotNewsOnIG #chicago #ShitCPDSays #Chicago #CPD #CubsWin #WorldSeries",
        "Duration": 43.337,
        "Url": "https://clyp.it/j2rfy52z",
        "Mp3Url": "http://a.clyp.it/j2rfy52z.mp3",
        "SecureMp3Url": "https://a.clyp.it/j2rfy52z.mp3",
        "OggUrl": "http://a.clyp.it/j2rfy52z.ogg",
        "SecureOggUrl": "https://a.clyp.it/j2rfy52z.ogg",
        "DateCreated": "2016-11-03T08:29:15.78"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "chicago",
        "AudioFileId": "u0jgjpof",
        "Title": "INTO THE LAKE",
        "Description": "#SpotNewsOnIG #CubsWin #WorldSeries #chicago #UnrulyFans #ShitCPDSays #CPD #Chicago",
        "Duration": 52.663,
        "Url": "https://clyp.it/u0jgjpof",
        "Mp3Url": "http://a.clyp.it/u0jgjpof.mp3",
        "SecureMp3Url": "https://a.clyp.it/u0jgjpof.mp3",
        "OggUrl": "http://a.clyp.it/u0jgjpof.ogg",
        "SecureOggUrl": "https://a.clyp.it/u0jgjpof.ogg",
        "DateCreated": "2016-11-03T07:51:31.313"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "chicago",
        "AudioFileId": "jv5cm20l",
        "Title": "GET THE FUCK ON THE GROUND!!!!",
        "Description": "#SpotNewsOnIG #chicago #ShitCPDSays #Chicago #CPD",
        "Duration": 7.079,
        "Url": "https://clyp.it/jv5cm20l",
        "Mp3Url": "http://a.clyp.it/jv5cm20l.mp3",
        "SecureMp3Url": "https://a.clyp.it/jv5cm20l.mp3",
        "OggUrl": "http://a.clyp.it/jv5cm20l.ogg",
        "SecureOggUrl": "https://a.clyp.it/jv5cm20l.ogg",
        "DateCreated": "2016-11-02T20:45:48.93"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "chicago",
        "AudioFileId": "bqwe45hp",
        "Title": "2 Lambos Shooting At Each Other",
        "Description": "#Chicago #SpotNewsOnIG #chicago",
        "Duration": 25.313,
        "Url": "https://clyp.it/bqwe45hp",
        "Mp3Url": "http://a.clyp.it/bqwe45hp.mp3",
        "SecureMp3Url": "https://a.clyp.it/bqwe45hp.mp3",
        "OggUrl": "http://a.clyp.it/bqwe45hp.ogg",
        "SecureOggUrl": "https://a.clyp.it/bqwe45hp.ogg",
        "DateCreated": "2016-10-29T16:55:44.98"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "chicago",
        "AudioFileId": "mjeafo1e",
        "Title": "Shots fired by the police, 59th/Princeton",
        "Description": "Audio starts at 10:04am.\n\nStory: http://www.chicagotribune.com/news/local/breaking/ct-1-wounded-during-englewood-police-shooting-20161023-story.html\n\n#chicago",
        "Duration": 766.537,
        "Url": "https://clyp.it/mjeafo1e",
        "Mp3Url": "http://a.clyp.it/mjeafo1e.mp3",
        "SecureMp3Url": "https://a.clyp.it/mjeafo1e.mp3",
        "OggUrl": "http://a.clyp.it/mjeafo1e.ogg",
        "SecureOggUrl": "https://a.clyp.it/mjeafo1e.ogg",
        "DateCreated": "2016-10-23T23:52:27.097"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "dubstep",
        "AudioFileId": "kvspuxfa",
        "Title": "Orchestral Dubstep WIP",
        "Description": "An orchestral dubstep thingy I started tonight, really like some of the sound design in this.\n\n#melodic_dubstep\n#orchestral_dubstep\n#orchestral\n#dubstep",
        "Duration": 12.852,
        "Url": "https://clyp.it/kvspuxfa",
        "Mp3Url": "http://a.clyp.it/kvspuxfa.mp3",
        "SecureMp3Url": "https://a.clyp.it/kvspuxfa.mp3",
        "OggUrl": "http://a.clyp.it/kvspuxfa.ogg",
        "SecureOggUrl": "https://a.clyp.it/kvspuxfa.ogg",
        "DateCreated": "2016-12-30T06:29:23.297"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "dubstep",
        "AudioFileId": "xyubdqqm",
        "Title": "MDC - Why Do They VIP (Feat. Shadowcat)",
        "Description": "#Mdc #WhyDoTheyVip #Dubstep",
        "Duration": 296.777,
        "Url": "https://clyp.it/xyubdqqm",
        "Mp3Url": "http://a.clyp.it/xyubdqqm.mp3",
        "SecureMp3Url": "https://a.clyp.it/xyubdqqm.mp3",
        "OggUrl": "http://a.clyp.it/xyubdqqm.ogg",
        "SecureOggUrl": "https://a.clyp.it/xyubdqqm.ogg",
        "DateCreated": "2016-12-29T16:24:56.56"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "dubstep",
        "AudioFileId": "tkij3ulm",
        "Title": "Glitch - ID",
        "Description": "#Dubstep",
        "Duration": 67.224,
        "Url": "https://clyp.it/tkij3ulm",
        "Mp3Url": "http://a.clyp.it/tkij3ulm.mp3",
        "SecureMp3Url": "https://a.clyp.it/tkij3ulm.mp3",
        "OggUrl": "http://a.clyp.it/tkij3ulm.ogg",
        "SecureOggUrl": "https://a.clyp.it/tkij3ulm.ogg",
        "DateCreated": "2016-12-29T10:46:27.993"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "dubstep",
        "AudioFileId": "ideu5al3",
        "Title": "DJ M.A.C. - Closer De Dum mp",
        "Description": "#DjMAC #CloserDeDumMp #Dubstep",
        "Duration": 226.586,
        "Url": "https://clyp.it/ideu5al3",
        "Mp3Url": "http://a.clyp.it/ideu5al3.mp3",
        "SecureMp3Url": "https://a.clyp.it/ideu5al3.mp3",
        "OggUrl": "http://a.clyp.it/ideu5al3.ogg",
        "SecureOggUrl": "https://a.clyp.it/ideu5al3.ogg",
        "DateCreated": "2016-12-29T06:35:40.323"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "dubstep",
        "AudioFileId": "4uifbhsn",
        "Title": "Glitch - ID",
        "Description": "#dubstep",
        "Duration": 64.032,
        "Url": "https://clyp.it/4uifbhsn",
        "Mp3Url": "http://a.clyp.it/4uifbhsn.mp3",
        "SecureMp3Url": "https://a.clyp.it/4uifbhsn.mp3",
        "OggUrl": "http://a.clyp.it/4uifbhsn.ogg",
        "SecureOggUrl": "https://a.clyp.it/4uifbhsn.ogg",
        "DateCreated": "2016-12-29T00:58:07.517"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "dubstep",
        "AudioFileId": "ciurtfu5",
        "Title": "MDC - Why Do They (Feat. Shadowcat) [28/12/16 20:55]",
        "Description": "#Mdc #WhyDoThey #Dubstep",
        "Duration": 225.176,
        "Url": "https://clyp.it/ciurtfu5",
        "Mp3Url": "http://a.clyp.it/ciurtfu5.mp3",
        "SecureMp3Url": "https://a.clyp.it/ciurtfu5.mp3",
        "OggUrl": "http://a.clyp.it/ciurtfu5.ogg",
        "SecureOggUrl": "https://a.clyp.it/ciurtfu5.ogg",
        "DateCreated": "2016-12-28T19:57:41.93"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "dubstep",
        "AudioFileId": "t3if5eul",
        "Title": "variation idea?",
        "Description": "#Mdc #WhyDoThey #Dubstep",
        "Duration": 27.22,
        "Url": "https://clyp.it/t3if5eul",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/f816da19d116444ea100711e442f7121.jpg",
        "Mp3Url": "http://a.clyp.it/t3if5eul.mp3",
        "SecureMp3Url": "https://a.clyp.it/t3if5eul.mp3",
        "OggUrl": "http://a.clyp.it/t3if5eul.ogg",
        "SecureOggUrl": "https://a.clyp.it/t3if5eul.ogg",
        "DateCreated": "2016-12-28T19:07:13.633"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "dubstep",
        "AudioFileId": "yr1eqsen",
        "Title": "MDC - Why Do They (Feat. Shadowcat)",
        "Description": "#Mdc #WhyDoThey #Dubstep",
        "Duration": 225.176,
        "Url": "https://clyp.it/yr1eqsen",
        "Mp3Url": "http://a.clyp.it/yr1eqsen.mp3",
        "SecureMp3Url": "https://a.clyp.it/yr1eqsen.mp3",
        "OggUrl": "http://a.clyp.it/yr1eqsen.ogg",
        "SecureOggUrl": "https://a.clyp.it/yr1eqsen.ogg",
        "DateCreated": "2016-12-28T17:46:10.2"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "dubstep",
        "AudioFileId": "uw5mfc4l",
        "Title": "ReZero - Stay Alive (Codly Remix)  (V4)",
        "Description": "Mixing stuff\nmore pad stuff\nadded break\nneed intro.\n\n#ReZero #Anime #weeb #MelodicDubstep #Dubstep",
        "Duration": 97.776,
        "Url": "https://clyp.it/uw5mfc4l",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/130cae9ae72d4dc7848a4d0244530bc5.jpg",
        "Mp3Url": "http://a.clyp.it/uw5mfc4l.mp3",
        "SecureMp3Url": "https://a.clyp.it/uw5mfc4l.mp3",
        "OggUrl": "http://a.clyp.it/uw5mfc4l.ogg",
        "SecureOggUrl": "https://a.clyp.it/uw5mfc4l.ogg",
        "DateCreated": "2016-12-28T11:36:23.343"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "dubstep",
        "AudioFileId": "fei3zepb",
        "Title": "Infini - Perish (Suffer VIP)",
        "Description": "#Infini #Perish #Dubstep",
        "Duration": 49.763,
        "Url": "https://clyp.it/fei3zepb",
        "Mp3Url": "http://a.clyp.it/fei3zepb.mp3",
        "SecureMp3Url": "https://a.clyp.it/fei3zepb.mp3",
        "OggUrl": "http://a.clyp.it/fei3zepb.ogg",
        "SecureOggUrl": "https://a.clyp.it/fei3zepb.ogg",
        "DateCreated": "2016-12-28T03:39:02.613"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "dubstep",
        "AudioFileId": "215abfof",
        "Title": "Stay Alive (Codly Remix)",
        "Description": "i'm kinda love the vocal so i made this.\n\n\n#ReZero #Melodic\n#Dubstep",
        "Duration": 36.989,
        "Url": "https://clyp.it/215abfof",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/b46f4137954f462088bcd760f3003255.jpg",
        "Mp3Url": "http://a.clyp.it/215abfof.mp3",
        "SecureMp3Url": "https://a.clyp.it/215abfof.mp3",
        "OggUrl": "http://a.clyp.it/215abfof.ogg",
        "SecureOggUrl": "https://a.clyp.it/215abfof.ogg",
        "DateCreated": "2016-12-28T03:21:26.04"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "dubstep",
        "AudioFileId": "d1ttbm4k",
        "Title": "Glitch - Silent",
        "Description": "#Dubstep",
        "Duration": 28.824,
        "Url": "https://clyp.it/d1ttbm4k",
        "Mp3Url": "http://a.clyp.it/d1ttbm4k.mp3",
        "SecureMp3Url": "https://a.clyp.it/d1ttbm4k.mp3",
        "OggUrl": "http://a.clyp.it/d1ttbm4k.ogg",
        "SecureOggUrl": "https://a.clyp.it/d1ttbm4k.ogg",
        "DateCreated": "2016-12-27T01:39:08.507"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "dubstep",
        "AudioFileId": "4tpvaubq",
        "Title": "MDC - Why Do They (Feat. Shadowcat)",
        "Description": "#Mdc #WhyDoThey #Dubstep",
        "Duration": 226.821,
        "Url": "https://clyp.it/4tpvaubq",
        "Mp3Url": "http://a.clyp.it/4tpvaubq.mp3",
        "SecureMp3Url": "https://a.clyp.it/4tpvaubq.mp3",
        "OggUrl": "http://a.clyp.it/4tpvaubq.ogg",
        "SecureOggUrl": "https://a.clyp.it/4tpvaubq.ogg",
        "DateCreated": "2016-12-25T22:56:23.493"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "dubstep",
        "AudioFileId": "j4xjrthb",
        "Title": "BitWare - Through The Distance (With... Miss Lina?)[if she accepts of course]",
        "Description": "#Bitware #ThroughTheDistance #Dubstep",
        "Duration": 80.64,
        "Url": "https://clyp.it/j4xjrthb",
        "Mp3Url": "http://a.clyp.it/j4xjrthb.mp3",
        "SecureMp3Url": "https://a.clyp.it/j4xjrthb.mp3",
        "OggUrl": "http://a.clyp.it/j4xjrthb.ogg",
        "SecureOggUrl": "https://a.clyp.it/j4xjrthb.ogg",
        "DateCreated": "2016-12-25T07:55:46.567"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "dubstep",
        "AudioFileId": "nqorlcsh",
        "Title": "Failed Attempt",
        "Description": "#mashup #mix #dubstep #electro #fail",
        "Duration": 83.252,
        "Url": "https://clyp.it/nqorlcsh",
        "Mp3Url": "http://a.clyp.it/nqorlcsh.mp3",
        "SecureMp3Url": "https://a.clyp.it/nqorlcsh.mp3",
        "OggUrl": "http://a.clyp.it/nqorlcsh.ogg",
        "SecureOggUrl": "https://a.clyp.it/nqorlcsh.ogg",
        "DateCreated": "2016-12-25T06:42:19.327"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "dubstep",
        "AudioFileId": "ed5zbbj0",
        "Title": "a wip",
        "Description": "#Dubstep #Riddim",
        "Duration": 58.149,
        "Url": "https://clyp.it/ed5zbbj0",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/7e57790bd23b4a95921f6576f725992f.jpg",
        "Mp3Url": "http://a.clyp.it/ed5zbbj0.mp3",
        "SecureMp3Url": "https://a.clyp.it/ed5zbbj0.mp3",
        "OggUrl": "http://a.clyp.it/ed5zbbj0.ogg",
        "SecureOggUrl": "https://a.clyp.it/ed5zbbj0.ogg",
        "DateCreated": "2016-12-25T02:52:31.117"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "dubstep",
        "AudioFileId": "fek5l3qk",
        "Title": "MDC - Sun and Moon (Original Mix)",
        "Description": "#Mdc #SunAndMoon #Dubstep",
        "Duration": 233.195,
        "Url": "https://clyp.it/fek5l3qk",
        "Mp3Url": "http://a.clyp.it/fek5l3qk.mp3",
        "SecureMp3Url": "https://a.clyp.it/fek5l3qk.mp3",
        "OggUrl": "http://a.clyp.it/fek5l3qk.ogg",
        "SecureOggUrl": "https://a.clyp.it/fek5l3qk.ogg",
        "DateCreated": "2016-12-23T17:57:16.01"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "dubstep",
        "AudioFileId": "4tmy52x3",
        "Title": "Carnivore - Things I'd Do",
        "Description": "#Carnivore #ThingsIdDo #Dubstep",
        "Duration": 212.611,
        "Url": "https://clyp.it/4tmy52x3",
        "Mp3Url": "http://a.clyp.it/4tmy52x3.mp3",
        "SecureMp3Url": "https://a.clyp.it/4tmy52x3.mp3",
        "OggUrl": "http://a.clyp.it/4tmy52x3.ogg",
        "SecureOggUrl": "https://a.clyp.it/4tmy52x3.ogg",
        "DateCreated": "2016-12-22T14:04:13.643"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "bass",
        "AudioFileId": "uitidc3v",
        "Title": "New Era",
        "Description": "https://soundcloud.com/kuhlkaktus\n\n#FutureBass #Future #Bass",
        "Duration": 211.566,
        "Url": "https://clyp.it/uitidc3v",
        "Mp3Url": "http://a.clyp.it/uitidc3v.mp3",
        "SecureMp3Url": "https://a.clyp.it/uitidc3v.mp3",
        "OggUrl": "http://a.clyp.it/uitidc3v.ogg",
        "SecureOggUrl": "https://a.clyp.it/uitidc3v.ogg",
        "DateCreated": "2016-12-28T18:09:44.53"
    },
    {
        "Status": "Public",
        "CommentsEnabled": true,
        "Category": "bass",
        "AudioFileId": "mbzj4hts",
        "Title": "Part of a full song but heres a small part of it",
        "Description": "#PartOfAFullSongButHeresASmallPartOfIt #FutureBass",
        "Duration": 69.59,
        "Url": "https://clyp.it/mbzj4hts",
        "Mp3Url": "http://a.clyp.it/mbzj4hts.mp3",
        "SecureMp3Url": "https://a.clyp.it/mbzj4hts.mp3",
        "OggUrl": "http://a.clyp.it/mbzj4hts.ogg",
        "SecureOggUrl": "https://a.clyp.it/mbzj4hts.ogg",
        "DateCreated": "2016-12-24T15:36:41.65"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "bass",
        "AudioFileId": "xbzvusya",
        "Title": "Polrock  - New Age (N4fy Remix)",
        "Description": "#Polrock #NewAge #FutureBass",
        "Duration": 191.634,
        "Url": "https://clyp.it/xbzvusya",
        "Mp3Url": "http://a.clyp.it/xbzvusya.mp3",
        "SecureMp3Url": "https://a.clyp.it/xbzvusya.mp3",
        "OggUrl": "http://a.clyp.it/xbzvusya.ogg",
        "SecureOggUrl": "https://a.clyp.it/xbzvusya.ogg",
        "DateCreated": "2016-12-24T12:02:45.587"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "bass",
        "AudioFileId": "q2xcpzqo",
        "Title": "Ciel à vendre, Babasmas - Ciel à Vendre - Laisse Rome, Laisse Bienne (Babasmas Remix)",
        "Description": "#CielAVendreBabasmas #CielAVendreLaisseRomeLaisseBienne #Lovetrap #frenchvocals #FutureBass #Lovetrap",
        "Duration": 236.852,
        "Url": "https://clyp.it/q2xcpzqo",
        "Mp3Url": "http://a.clyp.it/q2xcpzqo.mp3",
        "SecureMp3Url": "https://a.clyp.it/q2xcpzqo.mp3",
        "OggUrl": "http://a.clyp.it/q2xcpzqo.ogg",
        "SecureOggUrl": "https://a.clyp.it/q2xcpzqo.ogg",
        "DateCreated": "2016-12-15T22:39:17.867"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "bass",
        "AudioFileId": "e4gdb05a",
        "Title": "prisma",
        "Description": "#futurebass",
        "Duration": 240.039,
        "Url": "https://clyp.it/e4gdb05a",
        "Mp3Url": "http://a.clyp.it/e4gdb05a.mp3",
        "SecureMp3Url": "https://a.clyp.it/e4gdb05a.mp3",
        "OggUrl": "http://a.clyp.it/e4gdb05a.ogg",
        "SecureOggUrl": "https://a.clyp.it/e4gdb05a.ogg",
        "DateCreated": "2016-12-14T04:47:12.223"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "bass",
        "AudioFileId": "dupeb3de",
        "Title": "Paper Skies - ID 3 {V4}",
        "Description": "Really went out of my comfort zone on this one\nInspired by \"San Holo - Light\" \nChords could be more full, but I kinda like em like this\nDoesnt have an intro\nSecond drop needs something more, but im still not sure what\nTell me what you think about it!\n#sanholo #futurebass #future #trap #futuretrap #music #edm #dubstep #melodic",
        "Duration": 103.445,
        "Url": "https://clyp.it/dupeb3de",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/8560d90f3f6545719a7bc4cb06d295c7.jpg",
        "Mp3Url": "http://a.clyp.it/dupeb3de.mp3",
        "SecureMp3Url": "https://a.clyp.it/dupeb3de.mp3",
        "OggUrl": "http://a.clyp.it/dupeb3de.ogg",
        "SecureOggUrl": "https://a.clyp.it/dupeb3de.ogg",
        "DateCreated": "2016-11-27T23:04:21.647"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "bass",
        "AudioFileId": "hkkazddn",
        "Title": "douknow//noudont//udontknow",
        "Description": "#udontknow #remix #trap #futurebass #music",
        "Duration": 97.071,
        "Url": "https://clyp.it/hkkazddn",
        "Mp3Url": "http://a.clyp.it/hkkazddn.mp3",
        "SecureMp3Url": "https://a.clyp.it/hkkazddn.mp3",
        "OggUrl": "http://a.clyp.it/hkkazddn.ogg",
        "SecureOggUrl": "https://a.clyp.it/hkkazddn.ogg",
        "DateCreated": "2016-11-27T20:49:15.877"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "bass",
        "AudioFileId": "21lgsxfi",
        "Title": "Another Future Bass",
        "Description": "#futurebass #bass",
        "Duration": 54.491,
        "Url": "https://clyp.it/21lgsxfi",
        "Mp3Url": "http://a.clyp.it/21lgsxfi.mp3",
        "SecureMp3Url": "https://a.clyp.it/21lgsxfi.mp3",
        "OggUrl": "http://a.clyp.it/21lgsxfi.ogg",
        "SecureOggUrl": "https://a.clyp.it/21lgsxfi.ogg",
        "DateCreated": "2016-11-26T17:07:11.693"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "bass",
        "AudioFileId": "r1kqkngt",
        "Title": "FLÜGGÅӘNKб€ČHIŒßØLĮÊN",
        "Description": "#FutureBass #Trap",
        "Duration": 64.601,
        "Url": "https://clyp.it/r1kqkngt",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/ea148bdc308148d1b8bfe34f2c53d926.jpg",
        "Mp3Url": "http://a.clyp.it/r1kqkngt.mp3",
        "SecureMp3Url": "https://a.clyp.it/r1kqkngt.mp3",
        "OggUrl": "http://a.clyp.it/r1kqkngt.ogg",
        "SecureOggUrl": "https://a.clyp.it/r1kqkngt.ogg",
        "DateCreated": "2016-11-26T09:35:16.923"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "bass",
        "AudioFileId": "hxhgre5z",
        "Title": "Skyhaven - Haze (Original Mix)",
        "Description": "#Skyhaven #Haze #FutureBass",
        "Duration": 249.522,
        "Url": "https://clyp.it/hxhgre5z",
        "Mp3Url": "http://a.clyp.it/hxhgre5z.mp3",
        "SecureMp3Url": "https://a.clyp.it/hxhgre5z.mp3",
        "OggUrl": "http://a.clyp.it/hxhgre5z.ogg",
        "SecureOggUrl": "https://a.clyp.it/hxhgre5z.ogg",
        "DateCreated": "2016-11-26T08:43:05.08"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "bass",
        "AudioFileId": "4jzi3lvg",
        "Title": "something",
        "Description": "the result of someone that makes heavy dubstep making future bass #future #futurebass #melodic #wow",
        "Duration": 24.32,
        "Url": "https://clyp.it/4jzi3lvg",
        "Mp3Url": "http://a.clyp.it/4jzi3lvg.mp3",
        "SecureMp3Url": "https://a.clyp.it/4jzi3lvg.mp3",
        "OggUrl": "http://a.clyp.it/4jzi3lvg.ogg",
        "SecureOggUrl": "https://a.clyp.it/4jzi3lvg.ogg",
        "DateCreated": "2016-11-25T15:27:57.09"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "bass",
        "AudioFileId": "y2uwlwjl",
        "Title": "amazing",
        "Description": "#techno #house #trance #futurebass",
        "Duration": 353.332,
        "Url": "https://clyp.it/y2uwlwjl",
        "Mp3Url": "http://a.clyp.it/y2uwlwjl.mp3",
        "SecureMp3Url": "https://a.clyp.it/y2uwlwjl.mp3",
        "OggUrl": "http://a.clyp.it/y2uwlwjl.ogg",
        "SecureOggUrl": "https://a.clyp.it/y2uwlwjl.ogg",
        "DateCreated": "2016-11-23T13:13:16.747"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "bass",
        "AudioFileId": "51nhuay2",
        "Title": "boombox cartel & quix - supernatural (ft. anjulie) [synktra remix]",
        "Description": "stream and vote https://soundcloud.com/synktra/supernatural #boomboxcartel #quix #anjulie #synktra #trap #hybrid #hybridtrap #moombah #moombahton #future #futurebass #remix",
        "Duration": 300.408,
        "Url": "https://clyp.it/51nhuay2",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/e077ea4560ab463a90166f338bfc3235.jpg",
        "Mp3Url": "http://a.clyp.it/51nhuay2.mp3",
        "SecureMp3Url": "https://a.clyp.it/51nhuay2.mp3",
        "OggUrl": "http://a.clyp.it/51nhuay2.ogg",
        "SecureOggUrl": "https://a.clyp.it/51nhuay2.ogg",
        "DateCreated": "2016-11-22T21:12:27.287"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "bass",
        "AudioFileId": "1l4jnjym",
        "Title": "Rustie - Big Catzzz (Porter Robinson Edit)",
        "Description": "#Rustie #BigCatzzz #SpeeeedyEdmBlog #FutureBass",
        "Duration": 195.318,
        "Url": "https://clyp.it/1l4jnjym",
        "Mp3Url": "http://a.clyp.it/1l4jnjym.mp3",
        "SecureMp3Url": "https://a.clyp.it/1l4jnjym.mp3",
        "OggUrl": "http://a.clyp.it/1l4jnjym.ogg",
        "SecureOggUrl": "https://a.clyp.it/1l4jnjym.ogg",
        "DateCreated": "2016-11-19T21:49:11.16"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "bass",
        "AudioFileId": "qxyutfj3",
        "Title": "Rustie - Big Catzzz (Porter Robinson Edit)",
        "Description": "#Rustie #BigCatzzz #SpeeeedyEdmBlog #FutureBass",
        "Duration": 195.318,
        "Url": "https://clyp.it/qxyutfj3",
        "Mp3Url": "http://a.clyp.it/qxyutfj3.mp3",
        "SecureMp3Url": "https://a.clyp.it/qxyutfj3.mp3",
        "OggUrl": "http://a.clyp.it/qxyutfj3.ogg",
        "SecureOggUrl": "https://a.clyp.it/qxyutfj3.ogg",
        "DateCreated": "2016-11-19T21:47:35.937"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "bass",
        "AudioFileId": "ek4e3gip",
        "Title": "Tvffy x Ahpelion - Dream Girl (WIP)",
        "Description": "#Future #Bass #FutureBass #Music #Happy #Tvffy #Tunes #Fun \n- I love you -\nwww.SoundCloud.com/tvffymusic",
        "Duration": 24.921,
        "Url": "https://clyp.it/ek4e3gip",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/443992aeeb894602bb636a5c802edbbc.jpg",
        "Mp3Url": "http://a.clyp.it/ek4e3gip.mp3",
        "SecureMp3Url": "https://a.clyp.it/ek4e3gip.mp3",
        "OggUrl": "http://a.clyp.it/ek4e3gip.ogg",
        "SecureOggUrl": "https://a.clyp.it/ek4e3gip.ogg",
        "DateCreated": "2016-11-19T17:54:44.073"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "bass",
        "AudioFileId": "yk2pocdq",
        "Title": "Eventide (GrossBeat)",
        "Description": "#Preview #Kaiv #Electronic #EDM #FutureBass #Random",
        "Duration": 211.984,
        "Url": "https://clyp.it/yk2pocdq",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/10df0829554b48b8bd33b52065955cbd.jpg",
        "Mp3Url": "http://a.clyp.it/yk2pocdq.mp3",
        "SecureMp3Url": "https://a.clyp.it/yk2pocdq.mp3",
        "OggUrl": "http://a.clyp.it/yk2pocdq.ogg",
        "SecureOggUrl": "https://a.clyp.it/yk2pocdq.ogg",
        "DateCreated": "2016-11-19T01:26:45.483"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "bass",
        "AudioFileId": "5cc2rex1",
        "Title": "future bass",
        "Description": "#FutureBass",
        "Duration": 22.309,
        "Url": "https://clyp.it/5cc2rex1",
        "Mp3Url": "http://a.clyp.it/5cc2rex1.mp3",
        "SecureMp3Url": "https://a.clyp.it/5cc2rex1.mp3",
        "OggUrl": "http://a.clyp.it/5cc2rex1.ogg",
        "SecureOggUrl": "https://a.clyp.it/5cc2rex1.ogg",
        "DateCreated": "2016-11-18T00:24:16.57"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "bass",
        "AudioFileId": "gumby4cb",
        "Title": "future bass",
        "Description": "#FutureBass",
        "Duration": 24.764,
        "Url": "https://clyp.it/gumby4cb",
        "Mp3Url": "http://a.clyp.it/gumby4cb.mp3",
        "SecureMp3Url": "https://a.clyp.it/gumby4cb.mp3",
        "OggUrl": "http://a.clyp.it/gumby4cb.ogg",
        "SecureOggUrl": "https://a.clyp.it/gumby4cb.ogg",
        "DateCreated": "2016-11-18T00:16:14.937"
    },
    {
        "Status": "Public",
        "CommentsEnabled": true,
        "Category": "bass",
        "AudioFileId": "vzeroth5",
        "Title": "Fake Love - Lady S x Tim Hox remix",
        "Description": "#hiphop #FutureBass #remix #FakeLove\n#FreeDownload #DJ #LadyS #TimHox",
        "Duration": 194.638,
        "Url": "https://clyp.it/vzeroth5",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/d60a62b8142c4534a722bdec6f6090d8.jpg",
        "Mp3Url": "http://a.clyp.it/vzeroth5.mp3",
        "SecureMp3Url": "https://a.clyp.it/vzeroth5.mp3",
        "OggUrl": "http://a.clyp.it/vzeroth5.ogg",
        "SecureOggUrl": "https://a.clyp.it/vzeroth5.ogg",
        "DateCreated": "2016-11-16T11:32:53.893"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "electronic",
        "AudioFileId": "5qq15e0w",
        "Title": "Solace",
        "Description": "#electronic #piano #strings #ambient #peaceful",
        "Duration": 195.84,
        "Url": "https://clyp.it/5qq15e0w",
        "Mp3Url": "http://a.clyp.it/5qq15e0w.mp3",
        "SecureMp3Url": "https://a.clyp.it/5qq15e0w.mp3",
        "OggUrl": "http://a.clyp.it/5qq15e0w.ogg",
        "SecureOggUrl": "https://a.clyp.it/5qq15e0w.ogg",
        "DateCreated": "2016-12-29T21:21:26.53"
    },
    {
        "Status": "Public",
        "CommentsEnabled": true,
        "Category": "electronic",
        "AudioFileId": "c1qi0obu",
        "Title": "Dreamer",
        "Description": "#Electronic",
        "Duration": 255.216,
        "Url": "https://clyp.it/c1qi0obu",
        "Mp3Url": "http://a.clyp.it/c1qi0obu.mp3",
        "SecureMp3Url": "https://a.clyp.it/c1qi0obu.mp3",
        "OggUrl": "http://a.clyp.it/c1qi0obu.ogg",
        "SecureOggUrl": "https://a.clyp.it/c1qi0obu.ogg",
        "DateCreated": "2016-12-29T16:52:29.263"
    },
    {
        "Status": "Public",
        "CommentsEnabled": true,
        "Category": "electronic",
        "AudioFileId": "pmmeyoj5",
        "Title": "Ariana Grande - Problem ft. Iggy Azalea",
        "Description": "Silly pop bootleg lolz.\n\n#ArianaGrande #ProblemFtIggyAzalea #Electronic #futurepop #futuretrap #futurehouse #cyberpop",
        "Duration": 212.062,
        "Url": "https://clyp.it/pmmeyoj5",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/ab986bf37f684cb1bbbb73fa29269e73.jpg",
        "Mp3Url": "http://a.clyp.it/pmmeyoj5.mp3",
        "SecureMp3Url": "https://a.clyp.it/pmmeyoj5.mp3",
        "OggUrl": "http://a.clyp.it/pmmeyoj5.ogg",
        "SecureOggUrl": "https://a.clyp.it/pmmeyoj5.ogg",
        "DateCreated": "2016-12-28T23:47:26.583"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "electronic",
        "AudioFileId": "xnvghbxd",
        "Title": "The Void Between Celestial Bodies",
        "Description": "https://soundcloud.com/kuhlkaktus\n\n#Midtempo #Electronic #Electronica #Bass",
        "Duration": 255.321,
        "Url": "https://clyp.it/xnvghbxd",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/a0b18e9cfc124934984cbb13da5ab014.jpg",
        "Mp3Url": "http://a.clyp.it/xnvghbxd.mp3",
        "SecureMp3Url": "https://a.clyp.it/xnvghbxd.mp3",
        "OggUrl": "http://a.clyp.it/xnvghbxd.ogg",
        "SecureOggUrl": "https://a.clyp.it/xnvghbxd.ogg",
        "DateCreated": "2016-12-28T18:40:07.103"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "electronic",
        "AudioFileId": "oe42b4u3",
        "Title": "Plastic Palms",
        "Description": "https://soundcloud.com/kuhlkaktus\n\n#House #Electronic #Electronica #Halftime #hileute",
        "Duration": 212.95,
        "Url": "https://clyp.it/oe42b4u3",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/a3c6f43606f14362ac17d4121e7f7b1a.jpg",
        "Mp3Url": "http://a.clyp.it/oe42b4u3.mp3",
        "SecureMp3Url": "https://a.clyp.it/oe42b4u3.mp3",
        "OggUrl": "http://a.clyp.it/oe42b4u3.ogg",
        "SecureOggUrl": "https://a.clyp.it/oe42b4u3.ogg",
        "DateCreated": "2016-12-28T18:33:02.687"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "electronic",
        "AudioFileId": "njkvclmo",
        "Title": "Logical.mp3",
        "Description": "yet another soundcloud artist who didn't tag their music properly. #piano #electronic #instrumental",
        "Duration": 408.973,
        "Url": "https://clyp.it/njkvclmo",
        "Mp3Url": "http://a.clyp.it/njkvclmo.mp3",
        "SecureMp3Url": "https://a.clyp.it/njkvclmo.mp3",
        "OggUrl": "http://a.clyp.it/njkvclmo.ogg",
        "SecureOggUrl": "https://a.clyp.it/njkvclmo.ogg",
        "DateCreated": "2016-12-27T02:13:18.05"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "electronic",
        "AudioFileId": "ov2ecy33",
        "Title": "DubZone",
        "Description": "#Dubstep \n#lmms\n#electronic music\n#screech house",
        "Duration": 221.179,
        "Url": "https://clyp.it/ov2ecy33",
        "Mp3Url": "http://a.clyp.it/ov2ecy33.mp3",
        "SecureMp3Url": "https://a.clyp.it/ov2ecy33.mp3",
        "OggUrl": "http://a.clyp.it/ov2ecy33.ogg",
        "SecureOggUrl": "https://a.clyp.it/ov2ecy33.ogg",
        "DateCreated": "2016-12-25T20:40:10.473"
    },
    {
        "Status": "Public",
        "CommentsEnabled": true,
        "Category": "electronic",
        "AudioFileId": "r0mqhlgp",
        "Title": "DJ VI In The Mix - 1216 X-Mas Special Sessio - Best Of Electronica Free Arranged By Myself",
        "Description": "°. .　　.　☾ °☆ 　. * ● ¸ .　　　★　° :.　 . • ○ ° ★　 .　 *　.　　　　　　. 　 ° 　. ● .　　★　　° ☾ °☆ 　¸. ● .　　★　　★ ° ☾ ☆ ¸. ¸ 　★　 :.　 . • ○ ° ★　 .　 *　.　.　　¸ .　　 ° 　¸. * ● ¸ .\n° ☾ ° 　¸. ● ¸ .　　★　° :.　 . • °\nMERRY X-MAS AND A HAPPY AND HEALTHY NEW YEAR\nIS WISHING YOU\nAND YOUR FAMILY\nh E i K o L a N d W e E r\naka. DJ VI In The Mix\nAnD sAnTa ClAuS\naka. DJ CLAUS ★ ° . .　\n#Trance #Electronic #Techno #Chillout #House #DJ VI #Edm 　　　.　☾ °☆",
        "Duration": 3064.477,
        "Url": "https://clyp.it/r0mqhlgp",
        "Mp3Url": "http://a.clyp.it/r0mqhlgp.mp3",
        "SecureMp3Url": "https://a.clyp.it/r0mqhlgp.mp3",
        "OggUrl": "http://a.clyp.it/r0mqhlgp.ogg",
        "SecureOggUrl": "https://a.clyp.it/r0mqhlgp.ogg",
        "DateCreated": "2016-12-25T12:10:13.56"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "electronic",
        "AudioFileId": "x4eem2bl",
        "Title": "trbll",
        "Description": "#electronic",
        "Duration": 170.064,
        "Url": "https://clyp.it/x4eem2bl",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/7c4e3f070212480cb69a67dc1d54e9ae.jpg",
        "Mp3Url": "http://a.clyp.it/x4eem2bl.mp3",
        "SecureMp3Url": "https://a.clyp.it/x4eem2bl.mp3",
        "OggUrl": "http://a.clyp.it/x4eem2bl.ogg",
        "SecureOggUrl": "https://a.clyp.it/x4eem2bl.ogg",
        "DateCreated": "2016-12-25T01:33:32.037"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "electronic",
        "AudioFileId": "pnif2rib",
        "Title": "Wayr & Yonaka - At It Again",
        "Description": "#House #PorterRobinson #EDM  #WIP #WorkInProgress #Madeon #Music #Midtempo #Electro #Collaboration #Dance #Electronic #Chill",
        "Duration": 72.072,
        "Url": "https://clyp.it/pnif2rib",
        "Mp3Url": "http://a.clyp.it/pnif2rib.mp3",
        "SecureMp3Url": "https://a.clyp.it/pnif2rib.mp3",
        "OggUrl": "http://a.clyp.it/pnif2rib.ogg",
        "SecureOggUrl": "https://a.clyp.it/pnif2rib.ogg",
        "DateCreated": "2016-12-24T10:51:07.987"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "electronic",
        "AudioFileId": "ldtwfamr",
        "Title": "MrChkn - Rivals",
        "Description": "This one's really Techno! And it's by MrChkn! :O :D #Other #Dubstep #Trap #Electronic #EDM #Dance #DJ #Music #First #Second #Third",
        "Duration": 88.085,
        "Url": "https://clyp.it/ldtwfamr",
        "Mp3Url": "http://a.clyp.it/ldtwfamr.mp3",
        "SecureMp3Url": "https://a.clyp.it/ldtwfamr.mp3",
        "OggUrl": "http://a.clyp.it/ldtwfamr.ogg",
        "SecureOggUrl": "https://a.clyp.it/ldtwfamr.ogg",
        "DateCreated": "2016-12-23T23:29:25.667"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "electronic",
        "AudioFileId": "lf3fv5ci",
        "Title": "Nima Alipour - Nima Alipour-Meditation",
        "Description": "#NimaAlipour #NimaAlipourMeditation #Single #Electronic",
        "Duration": 220.056,
        "Url": "https://clyp.it/lf3fv5ci",
        "Mp3Url": "http://a.clyp.it/lf3fv5ci.mp3",
        "SecureMp3Url": "https://a.clyp.it/lf3fv5ci.mp3",
        "OggUrl": "http://a.clyp.it/lf3fv5ci.ogg",
        "SecureOggUrl": "https://a.clyp.it/lf3fv5ci.ogg",
        "DateCreated": "2016-12-23T19:57:46.287"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "electronic",
        "AudioFileId": "yjhajhuk",
        "Title": "Nine Inch Nails - 9 Ghosts I (cede remix) [wip preview]",
        "Description": "#electronic #industrial #rock #triphop",
        "Duration": 90.044,
        "Url": "https://clyp.it/yjhajhuk",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/ae444a8411764036a2547a9dbca1cdb3.jpg",
        "Mp3Url": "http://a.clyp.it/yjhajhuk.mp3",
        "SecureMp3Url": "https://a.clyp.it/yjhajhuk.mp3",
        "OggUrl": "http://a.clyp.it/yjhajhuk.ogg",
        "SecureOggUrl": "https://a.clyp.it/yjhajhuk.ogg",
        "DateCreated": "2016-12-23T06:20:09.63"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "electronic",
        "AudioFileId": "rwyum40j",
        "Title": "Dreamer",
        "Description": "#Electronic",
        "Duration": 114.181,
        "Url": "https://clyp.it/rwyum40j",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/14ed527412b3448db2ca54088518409c.jpg",
        "Mp3Url": "http://a.clyp.it/rwyum40j.mp3",
        "SecureMp3Url": "https://a.clyp.it/rwyum40j.mp3",
        "OggUrl": "http://a.clyp.it/rwyum40j.ogg",
        "SecureOggUrl": "https://a.clyp.it/rwyum40j.ogg",
        "DateCreated": "2016-12-22T21:44:52.717"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "electronic",
        "AudioFileId": "kyc5ir3w",
        "Title": "Mr. Scruff - Kalimba",
        "Description": "#MrScruff #Kalimba #NinjaTuna #Electronic",
        "Duration": 348.056,
        "Url": "https://clyp.it/kyc5ir3w",
        "Mp3Url": "http://a.clyp.it/kyc5ir3w.mp3",
        "SecureMp3Url": "https://a.clyp.it/kyc5ir3w.mp3",
        "OggUrl": "http://a.clyp.it/kyc5ir3w.ogg",
        "SecureOggUrl": "https://a.clyp.it/kyc5ir3w.ogg",
        "DateCreated": "2016-12-22T19:10:40.27"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "electronic",
        "AudioFileId": "53nhuwdc",
        "Title": "H'mmm Let's have some fun!",
        "Description": "#Funk #Electronic",
        "Duration": 89.704,
        "Url": "https://clyp.it/53nhuwdc",
        "Mp3Url": "http://a.clyp.it/53nhuwdc.mp3",
        "SecureMp3Url": "https://a.clyp.it/53nhuwdc.mp3",
        "OggUrl": "http://a.clyp.it/53nhuwdc.ogg",
        "SecureOggUrl": "https://a.clyp.it/53nhuwdc.ogg",
        "DateCreated": "2016-12-22T11:00:46.253"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "electronic",
        "AudioFileId": "t1f1f5ln",
        "Title": "Floating",
        "Description": "How come I am not featured yet? this stuff is great! XD\n#electronic\nEnjoy the new Tempo.",
        "Duration": 384.052,
        "Url": "https://clyp.it/t1f1f5ln",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/8a7914a94cd64725b033e8543d5d3301.jpg",
        "Mp3Url": "http://a.clyp.it/t1f1f5ln.mp3",
        "SecureMp3Url": "https://a.clyp.it/t1f1f5ln.mp3",
        "OggUrl": "http://a.clyp.it/t1f1f5ln.ogg",
        "SecureOggUrl": "https://a.clyp.it/t1f1f5ln.ogg",
        "DateCreated": "2016-12-21T18:36:24.417"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "electronic",
        "AudioFileId": "luqzr3an",
        "Title": "Ryuichi Sakamoto - You (Opening) (NHK 1982)",
        "Description": "#RyuichiSakamoto #You #Cm_tv #Electronic",
        "Duration": 96.94,
        "Url": "https://clyp.it/luqzr3an",
        "Mp3Url": "http://a.clyp.it/luqzr3an.mp3",
        "SecureMp3Url": "https://a.clyp.it/luqzr3an.mp3",
        "OggUrl": "http://a.clyp.it/luqzr3an.ogg",
        "SecureOggUrl": "https://a.clyp.it/luqzr3an.ogg",
        "DateCreated": "2016-12-21T06:05:03.987"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "electronic",
        "AudioFileId": "4bzcoacu",
        "Title": "Ryuichi Sakamoto - Put Your Hands Up (Ending) (TBS News 23 1997)",
        "Description": "#RyuichiSakamoto #PutYourHandsUp #Cm_tv #Electronic",
        "Duration": 91.533,
        "Url": "https://clyp.it/4bzcoacu",
        "Mp3Url": "http://a.clyp.it/4bzcoacu.mp3",
        "SecureMp3Url": "https://a.clyp.it/4bzcoacu.mp3",
        "OggUrl": "http://a.clyp.it/4bzcoacu.ogg",
        "SecureOggUrl": "https://a.clyp.it/4bzcoacu.ogg",
        "DateCreated": "2016-12-21T06:03:26.483"
    },
    {
        "Status": "DownloadDisabled",
        "CommentsEnabled": true,
        "Category": "electronic",
        "AudioFileId": "jsgxlkrc",
        "Title": "untenable tattle [wip]",
        "Description": "#industrial #electronic #rock",
        "Duration": 86.126,
        "Url": "https://clyp.it/jsgxlkrc",
        "ArtworkPictureUrl": "https://static.clyp.it/user-content/audio-file-artwork/6aea7b02604f44349313a3b0dec22719.jpg",
        "Mp3Url": "http://a.clyp.it/jsgxlkrc.mp3",
        "SecureMp3Url": "https://a.clyp.it/jsgxlkrc.mp3",
        "OggUrl": "http://a.clyp.it/jsgxlkrc.ogg",
        "SecureOggUrl": "https://a.clyp.it/jsgxlkrc.ogg",
        "DateCreated": "2016-12-21T05:29:49.587"
    }
];

module.exports = songs;